import type { Appointment, Doctor, Invoice, Patient, Prescription } from "./types";

export const iso = (d: Date) => d.toISOString().slice(0, 10);

export const shiftDays = (offset: number) => {
  const d = new Date();
  d.setHours(12, 0, 0, 0);
  d.setDate(d.getDate() + offset);
  return iso(d);
};

export const today = () => shiftDays(0);

export const weekdayOf = (dateStr: string) =>
  ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"][new Date(`${dateStr}T12:00:00`).getDay()]!;

export const prettyDate = (dateStr: string) =>
  new Date(`${dateStr}T12:00:00`).toLocaleDateString("en-US", {
    weekday: "short",
    month: "short",
    day: "numeric",
  });

export const money = (n: number) =>
  n.toLocaleString("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 });

export const doctors: Doctor[] = [
  {
    id: "d1",
    name: "Dr. Marcus Vance",
    specialty: "Cardiology",
    fee: 180,
    days: ["Mon", "Tue", "Thu", "Fri"],
    slots: ["09:00 AM", "09:45 AM", "10:30 AM", "11:15 AM", "02:00 PM", "02:45 PM"],
    active: true,
    bio: "Interventional cardiologist with 14 years treating arrhythmia and hypertension.",
    room: "Suite 204",
  },
  {
    id: "d2",
    name: "Dr. Elena Rostova",
    specialty: "General Medicine",
    fee: 95,
    days: ["Mon", "Wed", "Thu", "Sat"],
    slots: ["08:30 AM", "09:15 AM", "10:00 AM", "11:30 AM", "03:00 PM", "03:45 PM", "04:30 PM"],
    active: true,
    bio: "Family physician focused on preventive care, diabetes and respiratory illness.",
    room: "Suite 110",
  },
  {
    id: "d3",
    name: "Dr. Imani Okafor",
    specialty: "Dermatology",
    fee: 130,
    days: ["Tue", "Wed", "Fri"],
    slots: ["10:00 AM", "10:45 AM", "11:30 AM", "01:30 PM", "02:15 PM"],
    active: true,
    bio: "Medical and cosmetic dermatology, chronic eczema and skin cancer screening.",
    room: "Suite 318",
  },
  {
    id: "d4",
    name: "Dr. Peter Lindqvist",
    specialty: "Orthopaedics",
    fee: 165,
    days: ["Thu", "Fri"],
    slots: ["09:00 AM", "10:00 AM", "11:00 AM"],
    active: false,
    bio: "Sports injury and joint replacement specialist. Currently on sabbatical.",
    room: "Suite 402",
  },
];

export const patients: Patient[] = [
  {
    id: "p1",
    name: "Sarah Jenkins",
    email: "sarah.jenkins@mail.com",
    phone: "(415) 555-0127",
    dob: "1991-04-18",
    gender: "Female",
    bloodType: "O+",
    allergies: ["Penicillin", "Pollen"],
    conditions: ["Mild hypertension", "Seasonal asthma"],
    address: "88 Elmwood Court, San Rafael, CA",
    emergency: { name: "Daniel Jenkins", relation: "Spouse", phone: "(415) 555-0192" },
  },
  {
    id: "p2",
    name: "Omar Haddad",
    email: "omar.haddad@mail.com",
    phone: "(415) 555-0341",
    dob: "1978-11-02",
    gender: "Male",
    bloodType: "A-",
    allergies: ["Sulfa drugs"],
    conditions: ["Type 2 diabetes"],
    address: "17 Marina Blvd, Sausalito, CA",
    emergency: { name: "Leila Haddad", relation: "Sister", phone: "(415) 555-0388" },
  },
  {
    id: "p3",
    name: "Grace Oyelaran",
    email: "grace.oye@mail.com",
    phone: "(628) 555-0210",
    dob: "1996-07-25",
    gender: "Female",
    bloodType: "B+",
    allergies: [],
    conditions: ["Eczema"],
    address: "5 Hawthorne Lane, San Francisco, CA",
    emergency: { name: "Tolu Oyelaran", relation: "Brother", phone: "(628) 555-0219" },
  },
  {
    id: "p4",
    name: "Henry Whitlock",
    email: "h.whitlock@mail.com",
    phone: "(510) 555-0466",
    dob: "1959-01-30",
    gender: "Male",
    bloodType: "AB+",
    allergies: ["Latex"],
    conditions: ["Atrial fibrillation", "High cholesterol"],
    address: "342 Ridgeway Ave, Oakland, CA",
    emergency: { name: "Martha Whitlock", relation: "Wife", phone: "(510) 555-0471" },
  },
  {
    id: "p5",
    name: "Nina Alvarez",
    email: "nina.alvarez@mail.com",
    phone: "(415) 555-0783",
    dob: "2001-09-14",
    gender: "Female",
    bloodType: "O-",
    allergies: ["Ibuprofen"],
    conditions: [],
    address: "12 Cortland St, San Francisco, CA",
    emergency: { name: "Rosa Alvarez", relation: "Mother", phone: "(415) 555-0790" },
  },
];

export const appointments: Appointment[] = [
  {
    id: "a1",
    patientId: "p1",
    doctorId: "d1",
    date: shiftDays(0),
    slot: "09:45 AM",
    reason: "Blood pressure follow-up",
    notes: "Readings have been higher in the mornings.",
    status: "Confirmed",
    createdAt: shiftDays(-5),
  },
  {
    id: "a2",
    patientId: "p4",
    doctorId: "d1",
    date: shiftDays(0),
    slot: "10:30 AM",
    reason: "Palpitations review",
    notes: "",
    status: "Confirmed",
    createdAt: shiftDays(-6),
  },
  {
    id: "a3",
    patientId: "p2",
    doctorId: "d2",
    date: shiftDays(0),
    slot: "11:30 AM",
    reason: "Diabetes quarterly check",
    notes: "Brings home glucose log.",
    status: "Confirmed",
    createdAt: shiftDays(-3),
  },
  {
    id: "a4",
    patientId: "p3",
    doctorId: "d3",
    date: shiftDays(1),
    slot: "10:45 AM",
    reason: "Eczema flare-up",
    notes: "",
    status: "Requested",
    createdAt: shiftDays(-1),
  },
  {
    id: "a5",
    patientId: "p5",
    doctorId: "d2",
    date: shiftDays(2),
    slot: "09:15 AM",
    reason: "Persistent cough",
    notes: "Two weeks, worse at night.",
    status: "Requested",
    createdAt: shiftDays(0),
  },
  {
    id: "a6",
    patientId: "p1",
    doctorId: "d2",
    date: shiftDays(3),
    slot: "03:00 PM",
    reason: "Asthma inhaler renewal",
    notes: "",
    status: "Requested",
    createdAt: shiftDays(0),
  },
  {
    id: "a7",
    patientId: "p1",
    doctorId: "d1",
    date: shiftDays(-14),
    slot: "09:00 AM",
    reason: "Chest tightness after exercise",
    notes: "",
    status: "Completed",
    createdAt: shiftDays(-20),
  },
  {
    id: "a8",
    patientId: "p1",
    doctorId: "d2",
    date: shiftDays(-45),
    slot: "10:00 AM",
    reason: "Annual physical",
    notes: "",
    status: "Completed",
    createdAt: shiftDays(-50),
  },
  {
    id: "a9",
    patientId: "p4",
    doctorId: "d1",
    date: shiftDays(-9),
    slot: "11:15 AM",
    reason: "Anticoagulant review",
    notes: "",
    status: "Completed",
    createdAt: shiftDays(-15),
  },
  {
    id: "a10",
    patientId: "p2",
    doctorId: "d2",
    date: shiftDays(-7),
    slot: "08:30 AM",
    reason: "Foot numbness",
    notes: "",
    status: "Completed",
    createdAt: shiftDays(-12),
  },
  {
    id: "a11",
    patientId: "p3",
    doctorId: "d3",
    date: shiftDays(-4),
    slot: "01:30 PM",
    reason: "Mole screening",
    notes: "",
    status: "Cancelled",
    createdAt: shiftDays(-10),
  },
  {
    id: "a12",
    patientId: "p5",
    doctorId: "d1",
    date: shiftDays(4),
    slot: "02:00 PM",
    reason: "Resting heart rate concern",
    notes: "",
    status: "Confirmed",
    createdAt: shiftDays(-2),
  },
];

export const prescriptions: Prescription[] = [
  {
    id: "rx1",
    appointmentId: "a7",
    patientId: "p1",
    doctorId: "d1",
    date: shiftDays(-14),
    diagnosis: "Exertional hypertension, no ischemic findings",
    medications: [
      { name: "Amlodipine", dosage: "5 mg", frequency: "Once daily, morning", duration: "30 days" },
      { name: "Aspirin", dosage: "81 mg", frequency: "Once daily with food", duration: "Ongoing" },
    ],
    notes: "Log blood pressure twice daily. Return in four weeks with the log.",
  },
  {
    id: "rx2",
    appointmentId: "a8",
    patientId: "p1",
    doctorId: "d2",
    date: shiftDays(-45),
    diagnosis: "Seasonal asthma, well controlled",
    medications: [
      {
        name: "Salbutamol inhaler",
        dosage: "100 mcg",
        frequency: "2 puffs as needed",
        duration: "As required",
      },
    ],
    notes: "Bloodwork unremarkable. Continue current routine and annual review.",
  },
  {
    id: "rx3",
    appointmentId: "a9",
    patientId: "p4",
    doctorId: "d1",
    date: shiftDays(-9),
    diagnosis: "Atrial fibrillation, rate controlled",
    medications: [
      { name: "Apixaban", dosage: "5 mg", frequency: "Twice daily", duration: "Ongoing" },
      { name: "Bisoprolol", dosage: "2.5 mg", frequency: "Once daily", duration: "90 days" },
    ],
    notes: "Avoid grapefruit. Report any unusual bruising immediately.",
  },
  {
    id: "rx4",
    appointmentId: "a10",
    patientId: "p2",
    doctorId: "d2",
    date: shiftDays(-7),
    diagnosis: "Early diabetic peripheral neuropathy",
    medications: [
      { name: "Metformin", dosage: "1000 mg", frequency: "Twice daily with meals", duration: "90 days" },
      { name: "Gabapentin", dosage: "300 mg", frequency: "At night", duration: "30 days" },
    ],
    notes: "Daily foot inspection. Podiatry referral placed.",
  },
];

export const invoices: Invoice[] = [
  {
    id: "INV-1041",
    appointmentId: "a7",
    patientId: "p1",
    doctorId: "d1",
    items: [
      { label: "Cardiology consultation", amount: 180 },
      { label: "ECG", amount: 60 },
    ],
    total: 240,
    status: "Paid",
    method: "Card",
    issuedAt: shiftDays(-14),
    paidAt: shiftDays(-14),
  },
  {
    id: "INV-1042",
    appointmentId: "a9",
    patientId: "p4",
    doctorId: "d1",
    items: [
      { label: "Cardiology consultation", amount: 180 },
      { label: "Blood panel", amount: 75 },
    ],
    total: 255,
    status: "Paid",
    method: "Insurance",
    issuedAt: shiftDays(-9),
    paidAt: shiftDays(-8),
  },
  {
    id: "INV-1043",
    appointmentId: "a10",
    patientId: "p2",
    doctorId: "d2",
    items: [{ label: "General consultation", amount: 95 }],
    total: 95,
    status: "Unpaid",
    issuedAt: shiftDays(-7),
  },
];
