// Bundles supabase/functions/carebridge-ai-v3/knowledge/*.md into knowledge.gen.ts,
// because Edge Functions cannot read loose files at runtime.
// Usage: node scripts/build-okf.mjs [--check]
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const dir = join(import.meta.dirname, "..", "supabase", "functions", "carebridge-ai-v3");
const knowledgeDir = join(dir, "knowledge");
const outFile = join(dir, "knowledge.gen.ts");

export function renderBundle(files) {
  const entries = files.map(
    ({ name, source }) => `  ${JSON.stringify(name)}:\n    ${JSON.stringify(source)},`,
  );
  return [
    "// Generated by scripts/build-okf.mjs from knowledge/*.md. Do not edit by hand.",
    "export const OKF_SOURCES: Record<string, string> = {",
    ...entries,
    "};",
    "",
  ].join("\n");
}

export function readKnowledge() {
  return readdirSync(knowledgeDir)
    .filter((name) => name.endsWith(".md"))
    .sort()
    .map((name) => ({
      name,
      source: readFileSync(join(knowledgeDir, name), "utf8").replace(/\r\n/g, "\n"),
    }));
}

if (process.argv[1] && import.meta.filename === process.argv[1]) {
  const bundle = renderBundle(readKnowledge());
  if (process.argv.includes("--check")) {
    const current = readFileSync(outFile, "utf8").replace(/\r\n/g, "\n");
    if (current !== bundle) {
      console.error("knowledge.gen.ts is out of date. Run: node scripts/build-okf.mjs");
      process.exit(1);
    }
    console.log("knowledge.gen.ts is up to date.");
  } else {
    writeFileSync(outFile, bundle);
    console.log(`Wrote ${outFile}`);
  }
}
